

const col_config = [
  {
    "field": "cloud_provider",
    "filter": true,
    "label": "Cloud",
    "required": true,
    "type": "Icon"
  },
  {
    "field": "account_id",
    "filter": true,
    "label": "Id",
    "required": false,
    "type": "Text"
  },
  {
    "field": "region",
    "filter": true,
    "label": "Region",
    "required": true,
    "type": "Text"
  },
  {
    "field": "status",
    "filter": true,
    "label": "Status",
    "required": false,
    "type": "Badge"
  },
  {
    "field": "created_at",
    "filter": false,
    "label": "Created On",
    "required": false
    ,
    "type": "Date"
  },
  {
    "field": "owner",
    "filter": true,
    "label": "Owner",
    "required": true,
    "type": "Text"
  },
  {
    "field": "project_name",
    "filter": true,
    "label": "Project",
    "required": true,
    "type": "Text"
  },
  {
    "field": "environment",
    "filter": true,
    "label": "Environment",
    "required": true,
    "type": "Text"
  }
]



const row_data = [
    {
        cloud_provider: "AWS",
        account_id: "aws-021",
        region: "us-west-2",
        status: "Inactive",
        created_at: "2024-07-25",
        owner: "maya",
        project_name: "Vega",
        environment: "Staging",
    },
    {
        cloud_provider: "GCP",
        account_id: "gcp-022",
        region: "asia-south1",
        status: "Pending",
        created_at: "2023-03-26",
        owner: "liam",
        project_name: "Rift",
        environment: "Development",
    },
    {
        cloud_provider: "GCP",
        account_id: "gcp-023",
        region: "asia-south1",
        status: "Inactive",
        created_at: "2023-05-10",
        owner: "rachel",
        project_name: "Andromeda",
        environment: "Production",
    },
    {
        cloud_provider: "AWS",
        account_id: "aws-024",
        region: "us-east-1",
        status: "Active",
        created_at: "2025-12-08",
        owner: "yara",
        project_name: "Galaxy",
        environment: "Staging",
    },
    {
        cloud_provider: "GCP",
        account_id: "gcp-025",
        region: "us-east4",
        status: "Active",
        created_at: "2024-04-12",
        owner: "sam",
        project_name: "Nova",
        environment: "Production",
    },
    {
        cloud_provider: "Azure",
        account_id: "azure-026",
        region: "centralus",
        status: "Active",
        created_at: "2024-01-22",
        owner: "sam",
        project_name: "Neon",
        environment: "Production",
    },
    {
        cloud_provider: "Azure",
        account_id: "azure-027",
        region: "eastus",
        status: "Inactive",
        created_at: "2024-02-12",
        owner: "frank",
        project_name: "Eagle",
        environment: "Staging",
    },
    {
        cloud_provider: "GCP",
        account_id: "gcp-028",
        region: "asia-south1",
        status: "Pending",
        created_at: "2024-08-19",
        owner: "rachel",
        project_name: "Artemis",
        environment: "Production",
    },
    {
        cloud_provider: "Azure",
        account_id: "azure-029",
        region: "eastus",
        status: "Active",
        created_at: "2023-03-26",
        owner: "tina",
        project_name: "Sirius",
        environment: "Production",
    },
    {
        cloud_provider: "GCP",
        account_id: "gcp-030",
        region: "europe-west1",
        status: "Inactive",
        created_at: "2023-11-12",
        owner: "irene",
        project_name: "Galaxy",
        environment: "Staging",
    },
    {
        cloud_provider: "AWS",
        account_id: "aws-031",
        region: "us-west-2",
        status: "Pending",
        created_at: "2023-05-18",
        owner: "kate",
        project_name: "Eagle",
        environment: "Staging",
    },
    {
        cloud_provider: "GCP",
        account_id: "gcp-032",
        region: "europe-west1",
        status: "Pending",
        created_at: "2024-08-29",
        owner: "alice",
        project_name: "Vega",
        environment: "Development",
    },
    {
        cloud_provider: "AWS",
        account_id: "aws-033",
        region: "us-west-2",
        status: "Active",
        created_at: "2024-11-30",
        owner: "kate",
        project_name: "Galaxy",
        environment: "Production",
    },
    {
        cloud_provider: "AWS",
        account_id: "aws-034",
        region: "eu-central-1",
        status: "Inactive",
        created_at: "2023-04-30",
        owner: "emma",
        project_name: "Gemini",
        environment: "Development",
    },
    {
        cloud_provider: "Azure",
        account_id: "azure-035",
        region: "eastus",
        status: "Pending",
        created_at: "2024-05-28",
        owner: "wendy",
        project_name: "Rift",
        environment: "Development",
    },
    {
        cloud_provider: "GCP",
        account_id: "gcp-036",
        region: "us-east4",
        status: "Pending",
        created_at: "2023-04-25",
        owner: "liam",
        project_name: "Helix",
        environment: "Staging",
    },
    {
        cloud_provider: "Azure",
        account_id: "azure-037",
        region: "eastus",
        status: "Active",
        created_at: "2025-04-25",
        owner: "alice",
        project_name: "Rift",
        environment: "Development",
    },
    {
        cloud_provider: "GCP",
        account_id: "gcp-038",
        region: "europe-west1",
        status: "Pending",
        created_at: "2024-11-30",
        owner: "grace",
        project_name: "Zephyr",
        environment: "Staging",
    },
    {
        cloud_provider: "Azure",
        account_id: "azure-039",
        region: "northcentralus",
        status: "Inactive",
        created_at: "2025-09-25",
        owner: "tina",
        project_name: "Artemis",
        environment: "Development",
    },
    {
        cloud_provider: "AWS",
        account_id: "aws-040",
        region: "eu-central-1",
        status: "Pending",
        created_at: "2025-06-20",
        owner: "bob",
        project_name: "Draco",
        environment: "Development",
    },
    {
        cloud_provider: "AWS",
        account_id: "aws-041",
        region: "us-east-1",
        status: "Active",
        created_at: "2023-08-16",
        owner: "zane",
        project_name: "Leo",
        environment: "Staging",
    },
    {
        cloud_provider: "GCP",
        account_id: "gcp-042",
        region: "asia-south1",
        status: "Pending",
        created_at: "2024-10-02",
        owner: "tina",
        project_name: "Nova",
        environment: "Staging",
    },
    {
        cloud_provider: "AWS",
        account_id: "aws-043",
        region: "us-west-2",
        status: "Active",
        created_at: "2024-07-25",
        owner: "frank",
        project_name: "Gemini",
        environment: "Production",
    },
    {
        cloud_provider: "GCP",
        account_id: "gcp-044",
        region: "asia-south1",
        status: "Active",
        created_at: "2023-06-09",
        owner: "xavier",
        project_name: "Lynx",
        environment: "Production",
    },
    {
        cloud_provider: "Azure",
        account_id: "azure-045",
        region: "eastus",
        status: "Inactive",
        created_at: "2025-12-11",
        owner: "xavier",
        project_name: "Atlas",
        environment: "Development",
    },
    {
        cloud_provider: "Azure",
        account_id: "azure-046",
        region: "westus2",
        status: "Active",
        created_at: "2025-10-20",
        owner: "sam",
        project_name: "Hydra",
        environment: "Production",
    },
    {
        cloud_provider: "GCP",
        account_id: "gcp-047",
        region: "us-central1",
        status: "Pending",
        created_at: "2025-11-19",
        owner: "wendy",
        project_name: "Nova",
        environment: "Development",
    },
    {
        cloud_provider: "AWS",
        account_id: "aws-048",
        region: "us-east-1",
        status: "Active",
        created_at: "2025-04-13",
        owner: "rachel",
        project_name: "Hydra",
        environment: "Development",
    },
    {
        cloud_provider: "Azure",
        account_id: "azure-049",
        region: "eastus",
        status: "Inactive",
        created_at: "2025-12-25",
        owner: "irene",
        project_name: "Cosmos",
        environment: "Staging",
    },
    {
        cloud_provider: "GCP",
        account_id: "gcp-050",
        region: "asia-south1",
        status: "Pending",
        created_at: "2025-08-24",
        owner: "olivia",
        project_name: "Artemis",
        environment: "Development",
    },
    {
        cloud_provider: "GCP",
        account_id: "gcp-051",
        region: "europe-west1",
        status: "Pending",
        created_at: "2025-07-25",
        owner: "tina",
        project_name: "Orion",
        environment: "Production",
    },
    {
        cloud_provider: "AWS",
        account_id: "aws-052",
        region: "us-west-2",
        status: "Active",
        created_at: "2025-08-15",
        owner: "zane",
        project_name: "Lynx",
        environment: "Production",
    },
    {
        cloud_provider: "Azure",
        account_id: "azure-053",
        region: "centralus",
        status: "Pending",
        created_at: "2023-06-04",
        owner: "yara",
        project_name: "Draco",
        environment: "Production",
    },
    {
        cloud_provider: "GCP",
        account_id: "gcp-054",
        region: "europe-west1",
        status: "Pending",
        created_at: "2023-01-21",
        owner: "carol",
        project_name: "Sirius",
        environment: "Production",
    },
    {
        cloud_provider: "Azure",
        account_id: "azure-055",
        region: "northcentralus",
        status: "Active",
        created_at: "2025-02-17",
        owner: "emma",
        project_name: "Helix",
        environment: "Production",
    },
    {
        cloud_provider: "AWS",
        account_id: "aws-056",
        region: "us-west-2",
        status: "Inactive",
        created_at: "2024-10-23",
        owner: "victor",
        project_name: "Zephyr",
        environment: "Development",
    },
    {
        cloud_provider: "AWS",
        account_id: "aws-057",
        region: "eu-central-1",
        status: "Inactive",
        created_at: "2024-07-23",
        owner: "henry",
        project_name: "Sirius",
        environment: "Production",
    },
    {
        cloud_provider: "GCP",
        account_id: "gcp-058",
        region: "us-east4",
        status: "Inactive",
        created_at: "2024-03-03",
        owner: "dave",
        project_name: "Helix",
        environment: "Production",
    },
    {
        cloud_provider: "AWS",
        account_id: "aws-059",
        region: "us-west-2",
        status: "Inactive",
        created_at: "2024-01-08",
        owner: "victor",
        project_name: "Eagle",
        environment: "Production",
    },
    {
        cloud_provider: "AWS",
        account_id: "aws-060",
        region: "ap-southeast-1",
        status: "Active",
        created_at: "2023-08-31",
        owner: "yara",
        project_name: "Lynx",
        environment: "Production",
    },
    {
        cloud_provider: "Azure",
        account_id: "azure-061",
        region: "eastus",
        status: "Pending",
        created_at: "2023-06-17",
        owner: "jack",
        project_name: "Sirius",
        environment: "Development",
    },
    {
        cloud_provider: "Azure",
        account_id: "azure-062",
        region: "westus2",
        status: "Active",
        created_at: "2024-07-26",
        owner: "emma",
        project_name: "Cosmos",
        environment: "Production",
    },
    {
        cloud_provider: "AWS",
        account_id: "aws-063",
        region: "eu-central-1",
        status: "Active",
        created_at: "2024-09-18",
        owner: "nathan",
        project_name: "Apollo",
        environment: "Development",
    },
    {
        cloud_provider: "AWS",
        account_id: "aws-064",
        region: "eu-central-1",
        status: "Pending",
        created_at: "2025-04-03",
        owner: "wendy",
        project_name: "Draco",
        environment: "Production",
    },
    {
        cloud_provider: "GCP",
        account_id: "gcp-065",
        region: "europe-west1",
        status: "Inactive",
        created_at: "2024-02-19",
        owner: "tina",
        project_name: "Pegasus",
        environment: "Staging",
    },
    {
        cloud_provider: "Azure",
        account_id: "azure-066",
        region: "northcentralus",
        status: "Active",
        created_at: "2024-10-30",
        owner: "zane",
        project_name: "Andromeda",
        environment: "Development",
    },
    {
        cloud_provider: "GCP",
        account_id: "gcp-067",
        region: "asia-south1",
        status: "Active",
        created_at: "2024-11-11",
        owner: "grace",
        project_name: "Titan",
        environment: "Production",
    },
    {
        cloud_provider: "AWS",
        account_id: "aws-068",
        region: "us-west-2",
        status: "Inactive",
        created_at: "2023-04-05",
        owner: "frank",
        project_name: "Eagle",
        environment: "Development",
    },
    {
        cloud_provider: "GCP",
        account_id: "gcp-069",
        region: "asia-south1",
        status: "Inactive",
        created_at: "2024-01-25",
        owner: "peter",
        project_name: "Draco",
        environment: "Production",
    },
    {
        cloud_provider: "GCP",
        account_id: "gcp-070",
        region: "us-central1",
        status: "Pending",
        created_at: "2024-12-03",
        owner: "grace",
        project_name: "Neon",
        environment: "Development",
    },
];


module.exports = {
  row_data,
  col_config
};